### ISSUE TITLE
Need develop branch.

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/paddle-onnx#10]
New feature or hot-fix should be pushed to `develop` branch first. The `master` branch should maintain the stable version. We can polish the conversion for `fit_a_line` model and when the model is well supported we can ship it to `master` branch. Please vote for this proposal.

**Comment by varunarora** [comment]
Yes!! Go for it @pkuyym. Sorry i should have set it up that way initially, but all the support from me.

**Comment by pkuyym** [comment]
`Develop` branch has been added.
