### ISSUE TITLE
Loading Paddle parameters

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/paddle-onnx#3]
We need to figure out whether Paddle params will be read:
- in C++ using an executor run, 
- in C++ using a new interface just for reading
- in Python, with logic identical to C++ logic

Additionally, we need to get on the same page with populating the graph with parameters

**Comment by kuke** [comment]
@varunarora Seems that no need extra C++ code to load parameters. There is a method in Fluid to fetch the parameters

https://github.com/PaddlePaddle/Paddle/blob/3874c3831c425b50ec1cc66c9db6df77003cc323/python/paddle/fluid/executor.py#L136-L146

**Comment by varunarora** [comment]
Stupid me @kuke. I thought it wasn't possible to use after using an load on an inference model. You have taken care of this.
