### ISSUE TITLE
Revise the design again for final review 

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/paddle-onnx#6]

**Comment by varunarora** [comment]
I am going to do this soon - any key areas you want me to focus on making sure look good, @kuke?

**Comment by kuke** [comment]
@varunarora Cool! Now we that have a prototype convertor (#19 may be more close to the final one), we should have more ideas about the section **How it works** in [design doc](https://github.com/PaddlePaddle/Paddle/pull/9296), and the **Project structure** is also different from our current implementation.  And you can also try to make the English expression more native and more grammatical, etc.

Thanks!

**Comment by varunarora** [comment]
I think we are good here, open if work is still needed.
